mysql:
  image: mysql
  ports:
    - "3306:3306"
  expose:
    - "3306"
  environment:
    - MYSQL_USER=elly
    - MYSQL_PASSWORD=smerry
    - MYSQL_DATABASE=db_messaggi
    - MYSQL_ROOT_PASSWORD=root
  volumes:
    - "./conf.d:/etc/mysql/conf.d:ro"